# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import service_pb2 as service__pb2


class MyServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CountPolynomial = channel.unary_unary(
                '/MyService/CountPolynomial',
                request_serializer=service__pb2.PolynomialTask.SerializeToString,
                response_deserializer=service__pb2.PolynomialResult.FromString,
                )
        self.GetHello = channel.unary_unary(
                '/MyService/GetHello',
                request_serializer=service__pb2.Null.SerializeToString,
                response_deserializer=service__pb2.Hello.FromString,
                )


class MyServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CountPolynomial(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetHello(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MyServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CountPolynomial': grpc.unary_unary_rpc_method_handler(
                    servicer.CountPolynomial,
                    request_deserializer=service__pb2.PolynomialTask.FromString,
                    response_serializer=service__pb2.PolynomialResult.SerializeToString,
            ),
            'GetHello': grpc.unary_unary_rpc_method_handler(
                    servicer.GetHello,
                    request_deserializer=service__pb2.Null.FromString,
                    response_serializer=service__pb2.Hello.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'MyService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MyService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CountPolynomial(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/MyService/CountPolynomial',
            service__pb2.PolynomialTask.SerializeToString,
            service__pb2.PolynomialResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetHello(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/MyService/GetHello',
            service__pb2.Null.SerializeToString,
            service__pb2.Hello.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
