# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\"\x06\n\x04Null\"5\n\x0ePolynomialTask\x12\t\n\x01x\x18\x01 \x01(\x05\x12\x18\n\x0c\x63oefficients\x18\x02 \x03(\x05\x42\x02\x10\x01\"\x1d\n\x10PolynomialResult\x12\t\n\x01y\x18\x01 \x01(\x05\"\x19\n\x05Hello\x12\x10\n\x08greeting\x18\x01 \x01(\t2]\n\tMyService\x12\x35\n\x0f\x43ountPolynomial\x12\x0f.PolynomialTask\x1a\x11.PolynomialResult\x12\x19\n\x08GetHello\x12\x05.Null\x1a\x06.Hellob\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _POLYNOMIALTASK.fields_by_name['coefficients']._options = None
  _POLYNOMIALTASK.fields_by_name['coefficients']._serialized_options = b'\020\001'
  _NULL._serialized_start=17
  _NULL._serialized_end=23
  _POLYNOMIALTASK._serialized_start=25
  _POLYNOMIALTASK._serialized_end=78
  _POLYNOMIALRESULT._serialized_start=80
  _POLYNOMIALRESULT._serialized_end=109
  _HELLO._serialized_start=111
  _HELLO._serialized_end=136
  _MYSERVICE._serialized_start=138
  _MYSERVICE._serialized_end=231
# @@protoc_insertion_point(module_scope)
